### ISSUE TITLE
Bug: Unable to staking

### ISSUE THREAD

**Issue by VictorTrustyDev** [dymensionxyz/dymension-rdk#232]
I got validator address from here
```bash
rollapp_evm --home ~/.roller/rollapp/ q sequencers sequencers
```
Which is ethmvaloper1k9uvtqy2d2vkjn22lvqeyapfn9mz37ls7urn3r

I tried to stake (amount equals 0.9 ETH)
```bash
rollapp_evm --home ~/.roller/rollapp/ --keyring-backend test tx staking delegate ethmvaloper1k9uvtqy2d2vkjn22lvqeyapfn9mz37ls7urn3r 900000000000000000uescan --from staker
```
I got tx error `failed to execute message; message index: 0: validator does not exist`.
It said validator does not exists so I tried to query the sequencer again, it does exists:
```bash
rollapp_evm --home ~/.roller/rollapp/ q sequencers sequencer ethmvaloper1k9uvtqy2d2vkjn22lvqeyapfn9mz37ls7urn3r
```
```yaml
sequencer:
  commission:
    commission_rates:
      max_change_rate: "0.000000000000000000"
      max_rate: "0.000000000000000000"
      rate: "0.000000000000000000"
    update_time: "1970-01-01T00:00:00Z"
  consensus_pubkey:
    '@type': /cosmos.crypto.ed25519.PubKey
    key: 1GU5eqz7L2yJHLuqCH+G3/UeNd0NgQf+HVOmnwR3f0s=
  delegator_shares: "0.000000000000000000"
  description:
    details: ""
    identity: ""
    moniker: ""
    security_contact: ""
    website: ""
  jailed: false
  min_self_delegation: "1"
  operator_address: ethmvaloper1k9uvtqy2d2vkjn22lvqeyapfn9mz37ls7urn3r
  status: BOND_STATUS_BONDED
  tokens: "1000000000000000000"
  unbonding_height: "0"
  unbonding_time: "1970-01-01T00:00:00Z"
```
